### ISSUE TITLE
Compatibility with WorldEdit/FastAsyncWorldEdit

### ISSUE THREAD

**Issue by k-jiang** [SydMontague/ServerMinimap#4]
Server spam exceptions while player walking around with the map on hand.

Tested with:
Spigot 1.13 git-Spigot-fe3ab0d-162bda9
FastAsyncWorldEdit 1.13 https://empcraft.com/fawe/download/
WorldGuard - FAWE edition for 1.13 https://empcraft.com/fawe/download/

```
[04:46:40 WARN]: java.lang.NullPointerException
[04:46:40 WARN]:        at com.boydti.fawe.bukkit.v0.BukkitQueue_0.toNative(BukkitQueue_0.java:179)
[04:46:40 WARN]:        at com.boydti.fawe.bukkit.util.ItemUtil.getNBT(ItemUtil.java:71)
[04:46:40 WARN]:        at com.sk89q.worldedit.bukkit.BukkitItemStack.getNbtData(BukkitItemStack.java:63)
[04:46:40 WARN]:        at com.boydti.fawe.util.BrushCache.getTool(BrushCache.java:41)
[04:46:40 WARN]:        at com.sk89q.worldedit.LocalSession.getTool(LocalSession.java:961)
[04:46:40 WARN]:        at com.sk89q.worldedit.LocalSession.getTool(LocalSession.java:956)
[04:46:40 WARN]:        at com.boydti.fawe.bukkit.listener.BrushListener.onPlayerMove(BrushListener.java:73)
[04:46:40 WARN]:        at sun.reflect.GeneratedMethodAccessor43.invoke(Unknown Source)
[04:46:40 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[04:46:40 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[04:46:40 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304)
[04:46:40 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[04:46:40 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
[04:46:40 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
[04:46:40 WARN]:        at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:931)
[04:46:40 WARN]:        at net.minecraft.server.v1_13_R1.PacketPlayInFlying.a(SourceFile:126)
[04:46:40 WARN]:        at net.minecraft.server.v1_13_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57)
[04:46:40 WARN]:        at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.a(SourceFile:10)
[04:46:40 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[04:46:40 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[04:46:40 WARN]:        at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198)
[04:46:40 WARN]:        at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:884)
[04:46:40 WARN]:        at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411)
[04:46:40 WARN]:        at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819)
[04:46:40 WARN]:        at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717)
[04:46:40 WARN]:        at java.lang.Thread.run(Thread.java:748)
```

**Comment by k-jiang** [comment]
Updated Spigot server to version 1.13.2 and this issue seems gone. Tested with PaperSpigot 1.13.2 build 474.
